# Generated by Django 3.0.3 on 2020-03-07 11:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=40)),
                ('url', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('((git|ssh|http(s)?)|(git@[\\w\\.]+))(:(//)?)([\\w\\.@\\:/\\-~]+)(\\.git)(/)?', 'Invalid git url')])),
                ('branches_to_track', models.CharField(blank=True, max_length=200)),
                ('default_branch', models.CharField(blank=True, max_length=40)),
                ('username', models.CharField(blank=True, max_length=80)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('base_directory', models.CharField(max_length=300, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Error'), (2, 'Cloning'), (3, 'Analyzing'), (4, 'Ok')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codice_repository',
                'unique_together': {('name', 'owner'), ('url', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Repository')),
            ],
            options={
                'db_table': 'codice_branch',
                'unique_together': {('name', 'repository')},
            },
        ),
    ]
