# Generated by Django 3.0.4 on 2020-03-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Error'), (2, 'Cloning'), (3, 'Cloned'), (4, 'Analyzing'), (5, 'Ok')]),
        ),
    ]
