# Generated by Django 3.0.4 on 2020-03-15 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0004_auto_20200308_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('((git|ssh|http(s)?)|(git@[\\w\\.]+)|file)(:(//)?)([\\w\\.@\\:/\\-~]+)(\\.git)(/)?', 'Invalid git url')]),
        ),
    ]
