# Generated by Django 3.0.4 on 2020-03-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repos', '0003_auto_20200308_1829'),
        ('developers', '0001_initial'),
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.Developer'),
        ),
        migrations.AddField(
            model_name='commit',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Branch'),
        ),
        migrations.AddField(
            model_name='commit',
            name='original_author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_author', related_query_name='original_authors', to='developers.Developer'),
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Repository'),
        ),
    ]
