# Generated by Django 3.0.4 on 2020-03-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0002_auto_20200308_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitStatistic',
            fields=[
                ('date', models.DateTimeField()),
                ('commit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='commits.Commit')),
                ('blame_loc', models.IntegerField()),
                ('impact', models.FloatField(default=0.0)),
                ('log_impact', models.FloatField(default=0.0)),
                ('raw_churn', models.FloatField(default=0.0)),
                ('self_churn', models.FloatField(default=0.0)),
                ('churn', models.FloatField(default=0.0)),
                ('raw_throughput', models.FloatField(default=0.0)),
                ('self_throughput', models.FloatField(default=0.0)),
                ('throughput', models.FloatField(default=0.0)),
                ('ownership', models.FloatField(default=0.0)),
                ('acum_lines', models.IntegerField()),
                ('acum_insertions', models.IntegerField()),
                ('acum_deletions', models.IntegerField()),
                ('net_result', models.IntegerField()),
                ('changes', models.IntegerField()),
                ('add_self', models.IntegerField(default=0)),
                ('del_self', models.IntegerField(default=0)),
                ('add_others', models.IntegerField(default=0)),
                ('del_others', models.IntegerField(default=0)),
                ('work_self', models.FloatField(default=0.0)),
                ('work_others', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'codice_commitstatistic',
            },
        ),
    ]
