# Generated by Django 3.0.4 on 2020-03-16 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_blame'),
        ('commits', '0003_commitstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitBlame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.IntegerField()),
                ('add_self', models.IntegerField(default=0)),
                ('add_others', models.IntegerField(default=0)),
                ('del_self', models.IntegerField(default=0)),
                ('del_others', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.Developer')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commits.Commit')),
            ],
            options={
                'db_table': 'codice_commitblame',
            },
        ),
    ]
