# Generated by Django 3.0.4 on 2020-03-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0004_commitblame'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['branch', 'repository', 'author'], name='codice_comm_branch__9736dd_idx'),
        ),
    ]
