# Generated by Django 3.0.4 on 2020-03-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0005_auto_20200323_2319'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commitblame',
            index=models.Index(fields=['commit'], name='codice_comm_commit__510dcd_idx'),
        ),
    ]
