# Generated by Django 3.0.4 on 2020-03-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0006_auto_20200324_0059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommitStatistic',
        ),
    ]
