# Generated by Django 3.1.6 on 2021-02-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0008_auto_20210218_2038'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commit',
            name='codice_comm_branch__9736dd_idx',
        ),
    ]
