# Generated by Django 3.0.4 on 2020-03-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20200314_2307'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='codice_file',
        ),
    ]
