# Generated by Django 3.0.4 on 2020-03-15 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_blame'),
        ('files', '0004_auto_20200314_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.IntegerField()),
                ('deleted', models.IntegerField()),
                ('knowledge', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.Developer')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.File')),
            ],
            options={
                'db_table': 'codice_fileknowledge',
            },
        ),
    ]
