# Generated by Django 3.0.4 on 2020-03-18 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_blame'),
        ('files', '0005_fileknowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='knowledge_owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developers.Developer'),
        ),
    ]
