# Generated by Django 3.0.4 on 2020-03-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_knowledge_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='changes',
        ),
    ]
