# Generated by Django 3.0.4 on 2020-03-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_remove_file_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='hotspot_weight',
        ),
    ]
