# Generated by Django 3.0.4 on 2020-03-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_remove_file_hotspot_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filechange',
            name='change_type',
        ),
    ]
