# Generated by Django 3.0.4 on 2020-03-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_remove_filechange_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechange',
            name='change_type',
            field=models.TextField(blank=True, max_length=1),
        ),
    ]
