# Generated by Django 3.0.4 on 2020-03-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0005_auto_20200315_1919'),
        ('files', '0010_filechange_change_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('filename', 'repository', 'branch')},
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['path', 'is_code'], name='codice_file_path_id_ff8db4_idx'),
        ),
        migrations.AddIndex(
            model_name='fileblame',
            index=models.Index(fields=['author'], name='codice_file_author__16957b_idx'),
        ),
    ]
