# Generated by Django 3.0.4 on 2020-03-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20200324_0039'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fileblame',
            index=models.Index(fields=['commit'], name='codice_file_commit__c2e933_idx'),
        ),
    ]
