# Generated by Django 3.0.4 on 2020-03-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_blame'),
        ('files', '0013_auto_20200324_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_author', to='developers.Developer'),
        ),
    ]
