# Generated by Django 3.0.12 on 2021-02-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_file_author'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filechange',
            index=models.Index(fields=['commit'], name='codice_file_commit__18f851_idx'),
        ),
    ]
