# Generated by Django 3.0.12 on 2021-02-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_auto_20210217_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='changes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='hotspot_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
