# Generated by Django 3.0.12 on 2021-02-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_auto_20210217_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filechange',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='filechange',
            name='repository',
        ),
        migrations.AddIndex(
            model_name='filechange',
            index=models.Index(fields=['file'], name='codice_file_file_id_e244e6_idx'),
        ),
    ]
