# Generated by Django 3.0.12 on 2021-02-18 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_auto_20210218_0312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileBlame',
        ),
    ]
