# Generated by Django 3.1.6 on 2021-02-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_auto_20210218_2252'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='codice_file_path_id_ff8db4_idx',
        ),
        migrations.RemoveIndex(
            model_name='filepath',
            name='codice_file_parent__04396c_idx',
        ),
    ]
