# Generated by Django 3.0.4 on 2020-03-08 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repos', '0003_auto_20200308_1829'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='committer', max_length=80)),
                ('is_alias_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developers.Developer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('repos', models.ManyToManyField(to='repos.Repository')),
            ],
            options={
                'db_table': 'codice_developer',
                'unique_together': {('email', 'owner')},
            },
        ),
    ]
