# Generated by Django 3.0.4 on 2020-03-14 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0004_auto_20200308_2345'),
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.IntegerField(default=0)),
                ('insertions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('net', models.IntegerField(default=0)),
                ('net_avg', models.IntegerField(default=0)),
                ('loc', models.IntegerField(default=0)),
                ('commits', models.IntegerField(default=0)),
                ('changes', models.IntegerField(default=0)),
                ('impact', models.FloatField(default=0.0)),
                ('log_impact', models.FloatField(default=0.0)),
                ('ownership', models.FloatField(default=0.0)),
                ('add_self', models.IntegerField(default=0)),
                ('del_self', models.IntegerField(default=0)),
                ('add_others', models.IntegerField(default=0)),
                ('del_others', models.IntegerField(default=0)),
                ('raw_churn', models.FloatField(default=0.0)),
                ('self_churn', models.FloatField(default=0.0)),
                ('churn', models.FloatField(default=0.0)),
                ('raw_throughput', models.FloatField(default=0.0)),
                ('self_throughput', models.FloatField(default=0.0)),
                ('throughput', models.FloatField(default=0.0)),
                ('work_self', models.FloatField(default=0.0)),
                ('work_others', models.FloatField(default=0.0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.Developer')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Branch')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Repository')),
            ],
            options={
                'db_table': 'codice_blame',
                'unique_together': {('author', 'repository', 'branch')},
            },
        ),
    ]
