# Generated by Django 3.1.6 on 2021-02-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_auto_20210216_2326'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='developer',
            name='codice_deve_email_4157e5_idx',
        ),
    ]
